import 'package:space_bombs_app/models/level_model.dart';

final List<LevelModel> levelsRepository = [
  LevelModel(
    id: 0,
    number: 1,
    difficulty: LevelDifficulty.easy,
    cardImages: [
      'assets/images/game/1.png',
      'assets/images/game/1.png',
      'assets/images/game/2.png',
      'assets/images/game/2.png',
      'assets/images/game/3.png',
      'assets/images/game/3.png',
      'assets/images/game/4.png',
      'assets/images/game/4.png',
      'assets/images/game/5.png',
      'assets/images/game/5.png',
      'assets/images/game/6.png',
      'assets/images/game/6.png',
      'assets/images/game/7.png',
      'assets/images/game/7.png',
      'assets/images/game/8.png',
      'assets/images/game/8.png',
      'assets/images/game/9.png',
      'assets/images/game/9.png',
      'assets/images/game/10.png',
      'assets/images/game/10.png',
      'assets/images/game/11.png',
      'assets/images/game/11.png',
      'assets/images/game/12.png',
      'assets/images/game/12.png',
      'assets/images/game/13.png',
      'assets/images/game/13.png',
    ],
    minutes: 3,
    seconds: 0,
  ),
  LevelModel(
    id: 1,
    number: 2,
    difficulty: LevelDifficulty.easy,
    cardImages: [
      'assets/images/game/1.png',
      'assets/images/game/1.png',
      'assets/images/game/2.png',
      'assets/images/game/2.png',
      'assets/images/game/3.png',
      'assets/images/game/3.png',
      'assets/images/game/4.png',
      'assets/images/game/4.png',
      'assets/images/game/5.png',
      'assets/images/game/5.png',
      'assets/images/game/6.png',
      'assets/images/game/6.png',
      'assets/images/game/7.png',
      'assets/images/game/7.png',
      'assets/images/game/8.png',
      'assets/images/game/8.png',
      'assets/images/game/9.png',
      'assets/images/game/9.png',
      'assets/images/game/10.png',
      'assets/images/game/10.png',
      'assets/images/game/11.png',
      'assets/images/game/11.png',
      'assets/images/game/12.png',
      'assets/images/game/12.png',
      'assets/images/game/13.png',
      'assets/images/game/13.png',
    ],
    minutes: 3,
    seconds: 0,
  ),
  LevelModel(
    id: 2,
    number: 1,
    difficulty: LevelDifficulty.normal,
    cardImages: [
      'assets/images/game/1.png',
      'assets/images/game/1.png',
      'assets/images/game/2.png',
      'assets/images/game/2.png',
      'assets/images/game/3.png',
      'assets/images/game/3.png',
      'assets/images/game/4.png',
      'assets/images/game/4.png',
      'assets/images/game/5.png',
      'assets/images/game/5.png',
      'assets/images/game/6.png',
      'assets/images/game/6.png',
      'assets/images/game/7.png',
      'assets/images/game/7.png',
      'assets/images/game/8.png',
      'assets/images/game/8.png',
      'assets/images/game/9.png',
      'assets/images/game/9.png',
      'assets/images/game/10.png',
      'assets/images/game/10.png',
      'assets/images/game/11.png',
      'assets/images/game/11.png',
      'assets/images/game/12.png',
      'assets/images/game/12.png',
      'assets/images/game/13.png',
      'assets/images/game/13.png',
    ],
    minutes: 1,
    seconds: 30,
  ),
  LevelModel(
    id: 3,
    number: 2,
    difficulty: LevelDifficulty.normal,
    cardImages: [
      'assets/images/game/1.png',
      'assets/images/game/1.png',
      'assets/images/game/2.png',
      'assets/images/game/2.png',
      'assets/images/game/3.png',
      'assets/images/game/3.png',
      'assets/images/game/4.png',
      'assets/images/game/4.png',
      'assets/images/game/5.png',
      'assets/images/game/5.png',
      'assets/images/game/6.png',
      'assets/images/game/6.png',
      'assets/images/game/7.png',
      'assets/images/game/7.png',
      'assets/images/game/8.png',
      'assets/images/game/8.png',
      'assets/images/game/9.png',
      'assets/images/game/9.png',
      'assets/images/game/10.png',
      'assets/images/game/10.png',
      'assets/images/game/11.png',
      'assets/images/game/11.png',
      'assets/images/game/12.png',
      'assets/images/game/12.png',
      'assets/images/game/13.png',
      'assets/images/game/13.png',
    ],
    minutes: 1,
    seconds: 30,
  ),
  LevelModel(
    id: 4,
    number: 1,
    difficulty: LevelDifficulty.hard,
    cardImages: [
      'assets/images/game/1.png',
      'assets/images/game/1.png',
      'assets/images/game/2.png',
      'assets/images/game/2.png',
      'assets/images/game/3.png',
      'assets/images/game/3.png',
      'assets/images/game/4.png',
      'assets/images/game/4.png',
      'assets/images/game/5.png',
      'assets/images/game/5.png',
      'assets/images/game/6.png',
      'assets/images/game/6.png',
      'assets/images/game/7.png',
      'assets/images/game/7.png',
      'assets/images/game/8.png',
      'assets/images/game/8.png',
      'assets/images/game/9.png',
      'assets/images/game/9.png',
      'assets/images/game/10.png',
      'assets/images/game/10.png',
      'assets/images/game/11.png',
      'assets/images/game/11.png',
      'assets/images/game/12.png',
      'assets/images/game/12.png',
      'assets/images/game/bomb.png',
      'assets/images/game/bomb.png'
    ],
    minutes: 1,
    seconds: 0,
  ),
  LevelModel(
    id: 5,
    number: 2,
    difficulty: LevelDifficulty.hard,
    cardImages: [
      'assets/images/game/1.png',
      'assets/images/game/1.png',
      'assets/images/game/2.png',
      'assets/images/game/2.png',
      'assets/images/game/3.png',
      'assets/images/game/3.png',
      'assets/images/game/4.png',
      'assets/images/game/4.png',
      'assets/images/game/5.png',
      'assets/images/game/5.png',
      'assets/images/game/6.png',
      'assets/images/game/6.png',
      'assets/images/game/7.png',
      'assets/images/game/7.png',
      'assets/images/game/8.png',
      'assets/images/game/8.png',
      'assets/images/game/9.png',
      'assets/images/game/9.png',
      'assets/images/game/10.png',
      'assets/images/game/10.png',
      'assets/images/game/11.png',
      'assets/images/game/11.png',
      'assets/images/game/12.png',
      'assets/images/game/12.png',
      'assets/images/game/bomb.png',
      'assets/images/game/bomb.png'
    ],
    minutes: 1,
    seconds: 0,
  ),
];
